/** @type {import('next').NextConfig} */
const nextConfig = {
    output: 'export',
    env: {
        TITLE: process.env.TITLE,
        ADA_FAN_COMM_API_URL: process.env.ADA_FAN_COMM_API_URL,
        // CONTRACT_ADDRESS_METAVERSE: process.env.CONTRACT_ADDRESS_METAVERSE,
        // CONTRACT_ADDRESS_GREETING_CARD: process.env.CONTRACT_ADDRESS_GREETING_CARD,
        // CONTRACT_ADDRESS_JPY: process.env.CONTRACT_ADDRESS_JPY,
        CONTRACT_ADDRESS_DIGITAL_ID: process.env.CONTRACT_ADDRESS_DIGITAL_ID,
        CONTRACT_ADDRESS_CHATDATA: process.env.CONTRACT_ADDRESS_CHATDATA,
        CONTRACT_ADDRESS_SUPERCHAT: process.env.CONTRACT_ADDRESS_SUPERCHAT,
        CONTRACT_ADDRESS_DIGITAL_ID_SS: process.env.CONTRACT_ADDRESS_DIGITAL_ID_SS,
        CONTRACT_ADDRESS_CHATDATA_SS: process.env.CONTRACT_ADDRESS_CHATDATA_SS,
        CONTRACT_ADDRESS_SUPERCHAT_SS: process.env.CONTRACT_ADDRESS_SUPERCHAT_SS,
        IS_TEST: process.env.IS_TEST
      }    
};

export default nextConfig;
